### ISSUE TITLE
how to sync all data from one wandb local server to another wandb local server

### ISSUE THREAD

**Issue by liswp** [wandb/server#113]
Hi Wandb team,

Thanks a lot again for all the support. 

How do we sync all data from one wandb local server to another wandb local server? 

Say the first server is server #1, and second is server #2. 

Concretely, how does one move all logs and data from server #1 to server #2, without deleting the existing, unique data already on server #2? Many thanks again.

**Comment by ArtsiomWB** [comment]
Hi @liswp! The easiest way of doing this would be first logging into your local server number one, and downloading all of the runs from the first server onto your local machine (you might already have all of the runs on your local machine, if you have run everything on that machine). After downloading all of the runs log into the other server. 

Then you'll (unfortunately) have to go and run `wandb sync ~/my_run_path/wandb/run-timestamp-runid` for all of the runs you've downloaded from your first server. 

For context, whenever wandb run is executed, it creates a /wandb folder in the pwd. Within /wandb there is a /run-timestamp-runid where all files, logs, etc. are stored for that run.

You would then need to run wandb sync ~/my_run_path/wandb/run-timestamp-runid in order to sync that particular run. The important part is to make sure that the command is run in the same directory as where the wandb directory is located. For more information, [here](https://docs.wandb.ai/ref/cli/wandb-sync) is the documentation for wandb sync.

**Comment by ArtsiomWB** [comment]
Hi there, I wanted to follow up on this request. Please let us know if we can be of further assistance or if your issue has been resolved.

**Comment by liswp** [comment]
Yes, problem solved. Many thanks.
