### ISSUE TITLE
Can't see the signup page

### ISSUE THREAD

**Issue by twmht** [wandb/server#119]
I can't see the signup page after setting up the docker server.

only login page was shown up.

from docker logs it seems normal.

![image](https://github.com/wandb/server/assets/1567200/cb02b902-5e48-4b25-b134-907ebcebe1e6)

Any idea?

**Comment by anmolmann** [comment]
@twmht , what do you see when you go to `http://localhost:8080` uri?

**Comment by twmht** [comment]
@anmolmann 

I need sometime to reproduce the problem.

btw, what are the limitations of the free license? I have seen we can use only 10 GB for storage? is this true even if i have huge local disk?

**Comment by anmolmann** [comment]
@twmht , are you an academic user, i.e., user at an academic institution? If yes, then academics have no limit on the amount of hours of tracking and receive up to 100GB of storage with artifacts included. For more details: please checkout our [pricing page](https://wandb.ai/site/pricing), under `Private Hosting` -> `Personal`.

Also, please let me know once you've reproduced the issue again on your end.

**Comment by twmht** [comment]
@anmolmann 

I just follow the installation guide

```
docker run --rm -d -v wandb:/vol -p 8050:8080 --name wandb-local wandb/local
```

I was browsing from the other machine, not localhost, so
in my browser i send a URL like https://my-server-ip/5050

and here are what i see after the loading

![image](https://github.com/wandb/server/assets/1567200/3b9c351e-56da-426d-bc14-082934b0e2a7)

**Comment by twmht** [comment]
Here are another screenshot after link to login page

![image](https://github.com/wandb/server/assets/1567200/f649e018-8f9b-430c-b970-dc8f59ef9c23)

**Comment by anmolmann** [comment]
@twmht , thanks for providing more context!
1. What happens when you type in the URI `https://my-server-ip:5050/signup`?
2. Did you previously try setting up wandb server too and did you delete the volume `wandb` before you tried setting up wandb server again? It is possible that the `wandb` volume you're using is from before and at that time you might've signed up so using this volume again this time around, you're not getting redirected to the signup page.
3. 
Please let me know. Also, we have [new server version out](https://github.com/wandb/server/releases) - if you could try upgrading your server version, that would be great too. Thanks!

**Comment by anmolmann** [comment]
Hi @twmht , I wanted to follow up on this request. Please let us know if we can be of further assistance or if your issue has been resolved.

**Comment by anmolmann** [comment]
Hi @twmht , since we have not heard back from you we are going to close this request. If you would like to re-open the conversation, please let us know!
