### ISSUE TITLE
Urgent! I lost my data, please kindly help!

### ISSUE THREAD

**Issue by wztdream** [wandb/server#120]
Dear wandb maintainer,
@vanpelt

I use wandb local on my personal computer for a long time, it is great! My PhD project are all recorded using wandb local. Recently I need a very important data for my project, but I can not login anymore, due to the license is over. I have thought wandb is free, which is my miss understanding. And I understand the charge too. But I think, at least wandb should provide a way for the users to transfer their data, which maybe very very important.

So, I am asking if it is possible re-open by license for at least one day to let me transfer my data? This is really important and urgent for me, and maybe also very important for other users.

Here is my account for my local server: wztdream@163.com
and my cloud count is https://wandb.ai/wztdream

BTW, I think current policy seems unreasonable, if the license is over, wandb blocks the access of the data but still allows to login data. But, I think the correct policy should be: forbid user to login new data, but still allows to access the old data. Because the data is personal recourse, it seems wandb should not block the access.

**Comment by thanos-wandb** [comment]
Hi @wztdream thanks for messaging us here, and for the feedback regarding the current policy. 

Since you're a personal user we [offer free license as mentioned here](https://docs.wandb.ai/guides/hosting/how-to-guides/basic-setup#generate-a-free-license). I have followed up with you by email and sent you a new local license extended for a further year, and you could contact us once it's about to expire to renew further. 

Please let us know if that worked for you.

**Comment by wztdream** [comment]
Thank you, so much, glad to know it is free for personal user.  wandb is great!
