### ISSUE TITLE
Error: `Unable to reach the backend api. If this perists, check the system logs.`

### ISSUE THREAD

**Issue by fzyzcjy** [wandb/server#139]
Hi thanks for the tool! However, when pasting the license and saves it, it gives this error:

![image](https://github.com/wandb/server/assets/5236035/48c7c0cb-da9d-4120-a795-d45f8e0f2bc4)

Logs:

```
sudo docker compose logs -f wandb
wandb-1  | *** Running /etc/my_init.d/01_enable-services.sh...
wandb-1  | *** Enabling production mode
wandb-1  | *** Running /etc/my_init.d/02_load-settings.sh...
wandb-1  | *** Loading settings...
wandb-1  | 2024/04/27 06:32:51 Created default user
wandb-1  | 2024/04/27 06:32:51 Generating new session key for auth...
wandb-1  | 2024/04/27 06:32:51 Generating new certificate and key for auth...
wandb-1  | *** Booting runit daemon...
wandb-1  | *** Runit started as PID 50
wandb-1  | *** Setting up mysql database...
wandb-1  | *** Starting wandb servers...
wandb-1  | *** Configuring minio...
wandb-1  | Bucket created successfully `local/local-files`.
wandb-1  | Successfully added arn:minio:sqs:wandb-local:_:redis
wandb-1  | *** Migrating database...
wandb-1  | Initialized random go rng seed: to fix set env var TEST_GO_RNG_SEED=5582457954524981298
wandb-1  | Invoking megabinary "migrate": GOMAXPROCS=28
wandb-1  | 2024/04/27 06:32:55 Running squash migration from version 0 to 214...
wandb-1  | 2024/04/27 06:32:56 Squash migration successful. Continuing with normal migrations...
wandb-1  | 215/u named_workspaces_unlock_view (4.194096ms)
wandb-1  | 216/u entity_config (14.343285ms)
wandb-1  | 217/u associated_project_id_runqueue_item (25.555112ms)
wandb-1  | 218/u server_entity_backfill (30.007442ms)
wandb-1  | 219/u rqi_template_vars (38.276014ms)
wandb-1  | 220/u server_org_entity_backfill_edge_case (42.391874ms)
wandb-1  | 221/u storage_partial_delta_table (52.699959ms)
wandb-1  | 222/u project_rate_limits (63.342734ms)
wandb-1  | Loading custom chart definitions...
wandb-1  | *** All services started
wandb-1  | *** Access W&B at http://localhost:8080

**Comment by mikolajkania** [comment]
I have the same problem and reported it to support **11 days ago**. No response since then.

Local.log from Docker:
wandb@7740e26b1ab3:~$ cat /var/log/local.log
2024/04/14 23:01:59 Server Listening on Port 8083
127.0.0.1 - - [14/Apr/2024:23:02:14 +0000] "GET /api/env HTTP/1.1" 200 5114
127.0.0.1 - - [14/Apr/2024:23:02:14 +0000] "GET /api/env HTTP/1.1" 200 5114
127.0.0.1 - - [14/Apr/2024:23:02:15 +0000] "GET /api/build HTTP/1.1" 200 111
127.0.0.1 - - [14/Apr/2024:23:02:37 +0000] "GET /api/env HTTP/1.1" 200 5074
127.0.0.1 - - [14/Apr/2024:23:02:37 +0000] "GET /api/env HTTP/1.1" 200 5114
127.0.0.1 - - [14/Apr/2024:23:02:38 +0000] "GET /api/build HTTP/1.1" 200 111
127.0.0.1 - - [14/Apr/2024:23:06:55 +0000] "GET / HTTP/1.1" 200 0
127.0.0.1 - - [14/Apr/2024:23:06:55 +0000] "GET /static/js/main.b1dfd46a.js HTTP/1.1" 200 0
127.0.0.1 - - [14/Apr/2024:23:06:55 +0000] "GET /static/css/main.c9951160.css HTTP/1.1" 200 0
127.0.0.1 - - [14/Apr/2024:23:06:55 +0000] "GET /static/media/source-sans-pro-v13-latin-regular.f74389bd42b524dffbb4.woff2 HTTP/1.1" 200 0
127.0.0.1 - - [14/Apr/2024:23:06:55 +0000] "GET /static/media/source-sans-pro-v13-latin-600.17c0392cf7fce9aceb9f.woff2 HTTP/1.1" 200 0
127.0.0.1 - - [14/Apr/2024:23:06:55 +0000] "GET /api/env HTTP/1.1" 200 5114
127.0.0.1 - - [14/Apr/2024:23:06:55 +0000] "GET /logo.png HTTP/1.1" 200 0
127.0.0.1 - - [14/Apr/2024:23:06:55 +0000] "GET /favicon.png HTTP/1.1" 200 0
127.0.0.1 - - [14/Apr/2024:23:06:55 +0000] "GET /static/media/icons.38c6d8bab26db77d8c80.woff2 HTTP/1.1" 200 0
127.0.0.1 - - [14/Apr/2024:23:06:55 +0000] "GET /static/media/source-sans-pro-v13-latin-700.ed37bc608c1680ca735f.woff2 HTTP/1.1" 200 0

I have this problem locally, remote endpoint is working fine. My W&B local version is 0.52.2.

I tried to follow this and it didn't help: https://github.com/wandb/server/issues/46

**Comment by fzyzcjy** [comment]
@mikolajkania Thank you! However I am using 8080 and it still errors :(

**Comment by fzyzcjy** [comment]
* platform: ubuntu 22.04
* command: the following docker compose

```
    wandb:
      image: wandb/local
      restart: always
      volumes:
        - /home/tom/wandb_data:/vol
      ports:
        - "8080:8080"
```

I do not use wandb now, and thus will re-run and collect logs the next time I try it. Thanks!

**Comment by fmamberti-wandb** [comment]
Hi @fzyzcjy , I wasn't able to replicate the issue on my side on the latest version of W&B Server Local - I will close this for now however, feel free to re-open and send us the debug bundle if you are still experiencing this when you set up a local server again.

**Comment by HernandoR** [comment]
I have the same issue here, and suspect it relating to the network to wandb. Could you kindly confirm if the add license process require network traffice to wandb? @fmamberti-wandb
